# Generated by Django 4.2.2 on 2023-06-24 08:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="uploads/")),
            ],
            options={
                "ordering": ("uploaded",),
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("processed", models.IntegerField(default=0)),
                ("total", models.IntegerField(default=0)),
                ("next_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
