# Generated by Django 4.2.2 on 2023-06-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="preview",
            field=models.ImageField(blank=True, null=True, upload_to="preview/"),
        ),
    ]
