# Generated by Django 4.2.2 on 2023-06-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0002_file_name_file_preview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={"ordering": ("-uploaded",)},
        ),
        migrations.CreateModel(
            name="FileImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                ("image", models.ImageField(upload_to="pages/")),
            ],
            options={
                "ordering": ("order",),
                "unique_together": {("order", "image")},
            },
        ),
    ]
