# Generated by Django 4.2.2 on 2023-06-24 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0003_alter_file_options_fileimage"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fileimage",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="fileimage",
            name="file",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="processor.file",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="fileimage",
            unique_together={("order", "file")},
        ),
    ]
