# Generated by Django 4.2.2 on 2023-06-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "processor",
            "0007_delete_task_remove_fileimage_text_file_ideal_title_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="processed_file",
            field=models.FileField(blank=True, null=True, upload_to="processed/"),
        ),
    ]
